### ISSUE TITLE
What should the base template provide?

### ISSUE THREAD

**Issue by seancorfield** [Frege/frege-lein-template#1]
Open issue: Pure Frege projects (powered by Leiningen) or Clojure/Frege projects?

If a main is added in the primary Frege code, would that address both?

**Comment by swr1bm86** [comment]
i support the first way.

maybe we should write a project manage tool in pure frege instead of write a leiningen plugin to mix clojure and frege in same project by default.

and i think write yet another project like leiningen is really cool and will benefit the frege community

**Comment by seancorfield** [comment]
Chatted to @zjhmale and I think we'll change the default template to be pure Frege and accept an optional argument to the template `:with-clojure` that produces the mixed Clojure/Frege version of today's template.

Given that #5 will update Frege with breaking changes, and this will be a breaking change to the template, it might be good to get both of these in for the same version.

**Comment by seancorfield** [comment]
Closing this as dealt with. The (pure) Frege template could probably have better generated tests and/or could use a better example than Fibonacci but that's really a separate issue at this point.
